### ISSUE TITLE
bap_parameters_t->requires field conflicts with C++20 keyword 'requires'

### ISSUE THREAD

**Issue by larkwiot** [BinaryAnalysisPlatform/bap-bindings#22]
The struct:
```C
struct bap_parameters_t {
  char** features; char** requires; char** library; char** argv;
  char*(* env)(char*); char* man; char* name; char* version; 
};
```
has the field `requires` which conflicts with the new (as of C++20) keyword "requires." (ref https://en.cppreference.com/w/cpp/keyword/requires)
The conflict makes bap-bindings incompatible with C++ when using C++20.

Screenshot of error: https://imgur.com/a/il0yYHu

I'm sure this can be easily resolved by renaming the field.

**Comment by ivg** [comment]
Just changing the name would break the backward compatibility, one of the main pillars of bap. We probably need some macro-magic to deal with it.

**Comment by ivg** [comment]
@larkwiot, what do you think about #23?

**Comment by larkwiot** [comment]
> @larkwiot, what do you think about #23?

That looks good at a glance, I will try it with that change tonight and confirm that it works.

**Comment by larkwiot** [comment]
Unfortunately doesn't seem to fix the issue. I'm not sure there's any good way to deal with this if renaming breaks backwards compatibility, since the compiler can't be stopped from identifying `requires` as being a keyword.

**Comment by ivg** [comment]
Why is it not fixing an issue? Can you elaborate a bit, like what kind of error do you get? And are you sure that you were using the newly generated header file?

**Comment by larkwiot** [comment]
gcc 10's __cplusplus value for `-std=c++20` is `201709L`, so a more strict comparison is needed (as you mentioned in gitter). Otherwise this solution is good!

**Comment by ivg** [comment]
> gcc 10's __cplusplus value for `-std=c++20` is `201709L`, so a more strict comparison is needed (as you mentioned in gitter). Otherwise this solution is good!

Yep, it is now `__cplusplus > 201703L`, merged!
