### ISSUE TITLE
 Unbound value

### ISSUE THREAD

**Issue by asis-team** [BinaryAnalysisPlatform/bap-bindings#7]
During make I got following errors: 
File "bap/lib/bindings.ml", line 755, characters 45-58:
Error: Unbound value Word.unsigned
Hint: Did you mean signed?
Makefile:75: recipe for target '_build/bap/lib/bindings.cmx' failed
make: *** [_build/bap/lib/bindings.cmx] Error 2

**Comment by ivg** [comment]
`Word.unsigned` was added on bap.1.3 so it looks like that you have an older version. Either upgrade BAP or downgrade bap-bindings

Note, BAP.1.3 is not yet in the official ocaml repository - the process usually takes some time, so you can get it by linking our opam-repository, e.g.,
```
opam repo add bap-v1.3 git://github.com/BinaryAnalysisPlatform/opam-repository#v1.3
```

**Comment by maurer** [comment]
If you're mostly just looking to use `bap-bindings`, and not extend bap through plugins or similar mechanisms, the [prebuilt artifacts](https://github.com/BinaryAnalysisPlatform/bap/releases/tag/v1.3.0) may be helpful to you. (To develop against `libbap` (what bap-bindings becomes) you'll need `bap`, `libbap`, and `libbap-dev`)
