### ISSUE TITLE
BAP Master/Core 0.9 incompat

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap-bindings#8]
When building against BAP master, using new core, I get
```
File "bap/lib/bindings.ml", line 450, characters 33-37:
Error: Signature mismatch:
       ...
       Values do not match:
         val mem :
           'a Regular.Std.seq -> 'a -> equal:('a -> 'a -> bool) -> bool
       is not included in
         val mem : t -> elt -> bool
```
I suspect this is related to the changed signatures in Core 0.9, since the update to Core 0.9 came after the 1.3 release cut.

**Comment by XVilka** [comment]
@maurer see https://github.com/BinaryAnalysisPlatform/bap/pull/820
